apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  mensaje: "Hola desde ConfigMap!"
  index.html: |
    <html>
      <body>
        <h1>Hola desde ArgoCD + GitOps!</h1>
      </body>
    </html>
